services:
  controller:
    build:
      context: ./docker/controller
    hostname: controller
    container_name: controller
    volumes:
      - ./ansible:/etc/ansible
      - ./shared/home:/home
      - ./shared/scratch:/scratch
    networks:
      - slurm-net

  node01:
    build:
      context: ./docker/worker
    hostname: node01
    container_name: node01
    volumes:
      - ./shared/home:/home
      - ./shared/scratch:/scratch
    networks:
      - slurm-net

  node02:
    build:
      context: ./docker/worker
    hostname: node02
    container_name: node02
    volumes:
      - ./shared/home:/home
      - ./shared/scratch:/scratch
    networks:
      - slurm-net

networks:
  slurm-net:
    driver: bridge
