---
- name: Test connectivity to all nodes
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

- import_playbook: munge.yml
- import_playbook: slurm.yml
