all:
  children:
    controllers:
      hosts:
        controller:
    workers:
      hosts:
        node01:
        node02:
  vars:
    ansible_password: ansible
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
